platform :ios, '8.0'

target 'Alonser' do

use_frameworks!

pod 'ObjectMapper'
pod 'Moya'
pod 'RxCocoa'
pod 'RxDataSources'

pod 'SnapKit'#约束#
pod "SDWebImage"
pod "IQKeyboardManagerSwift"
pod 'WechatOpenSDK'

pod 'XCGLogger'

end
